### ISSUE TITLE
Issue in model.py

### ISSUE THREAD

**Issue by 27Apoorva** [themightyoarfish/deepVO#1]
ValueError: 'conv{index}' is not a valid scope name

**Comment by themightyoarfish** [comment]
Provide more information and I'll reopen.

**Comment by 27Apoorva** [comment]
Hi, 
Thank you for your response. I am sorry for not being specific before.
I am trying to run your code for KITTI Dataset Grey scale images and poses. Basically, I have raw KITTI data image and poses. I have set up the datamanager.py to read .png images and .txt poses. 
When I am trying to train, model.py is throwing error.
I am running this command:
$ python3 main.py -d /home/appu/DeepLearning/Project/Deep-Learning-for-Point-Cloud/Point\ Cloud/2011_09_26/2011_09_26_drive_0001_extract/ -o Adam -l 0.01 -b 10 -e 3 -m 10 -s 11
This is my output:

Number of batches for training: 1
Number of batches for testing: 1
DataManager found 114 images and poses in dataset.
Image shape: (512, 1392, 3)
> /home/appu/DeepLearning/Project/deepVO/model.py(84)__init__()
-> with tf.variable_scope('inputs'):
(Pdb) c
w: inputs/imgs:0
> /home/appu/DeepLearning/Project/deepVO/model.py(109)__init__()
-> cnn_activation = self.cnn(stacked_image,ksizes,strides,n_channels,reuse=tf.AUTO_REUSE)
(Pdb) c
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main()
  File "main.py", line 81, in main
    use_flownet=args.flownet is not None)
  File "/home/appu/DeepLearning/Project/deepVO/model.py", line 109, in __init__
    cnn_activation = self.cnn(stacked_image,ksizes,strides,n_channels,reuse=tf.AUTO_REUSE)
  File "/home/appu/DeepLearning/Project/deepVO/model.py", line 230, in cnn
    with tf.variable_scope(inner_scope_name):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 1903, in __enter__
    return self._enter_scope_uncached()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/variable_scope.py", line 1947, in _enter_scope_uncached
    current_name_scope_name = current_name_scope.__enter__()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 5775, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 3979, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'conv{index}' is not a valid scope name

Please tell me what I am doing wrong and if you need any more information.
Thank you.

**Comment by themightyoarfish** [comment]
I see. Python 3.6 is required, since format strings are not supported in previous versions.

**Comment by themightyoarfish** [comment]
Also, be advised we didn't actually run this on the KITTI dataset since we could not even fit our own data into GPU memory with reasonable parameters. I'm not sure if the implementation is correct.
